FROM base-builder:bookworm AS builder

ARG NVIM_VERSION
WORKDIR /src

# Use the prebuilt AppImage (fail if missing)
RUN curl -fL -o nvim.appimage https://github.com/neovim/neovim/releases/download/v${NVIM_VERSION}/nvim.appimage \
    && chmod u+x nvim.appimage \
    && ./nvim.appimage --appimage-extract \
    && mv squashfs-root /nvim \
    && rm nvim.appimage