FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl xz-utils fuse squashfs-tools ca-certificates \
 && update-ca-certificates \
 && rm -rf /var/lib/apt/lists/*